// Generated by scripts/gen-icons.mjs. Do not edit; run `npm run icons`.

/** The MoucX cube mark on a 100x100 canvas: the M, then its top face. */
export const MARK_BODY = "M 16.619 35.246 L 50 57.444 L 83.381 35.246 L 83.381 77.139 L 70.73 84.983 L 70.73 57.444 L 50 72.365 L 29.27 57.444 L 29.27 84.983 L 16.619 77.139 Z"
export const MARK_LID = "M 50 14.997 L 80.377 32.008 L 50 49.019 L 19.623 32.008 Z"
